### ISSUE TITLE
Closing ssh tunnel from menu option does not seem to work

### ISSUE THREAD

**Issue by joshjriley** [KeckObservatory/RemoteObserving#10]
I closed the tunnel port to an open vnc session using the 'c' option but the vnc session still stayed open and I could still interact with it normally.

**Comment by joshwalawender** [comment]
I see similar behavior, but it seems to be consistent with the `q` behavior: I need to close the vncviewer windows to have the quit process finish.  I tried this on my Mac and got the behavior consistently regardless of what VNC viewer client I was using.

Inside the Keck firewall where there are no sshtunnels, this behavior is different.  The windows all close for me on `q`.

**Comment by joshwalawender** [comment]
See if #22 affects this.

**Comment by joshwalawender** [comment]
I never dug in to this or reproduced the exact problem.  @joshriley can you see if #22 (the current dev branch) fixed this?

**Comment by joshjriley** [comment]
This seems to have been fixed as a byproduct to going to the direct ssh method instead of using sshtunnel module.  Closing an sshtunnel from the menu will close the vnc session.
