### ISSUE TITLE
Soundplay Issue with M2 Mac

### ISSUE THREAD

**Issue by prappleizer** [KeckObservatory/RemoteObserving#102]
Similar (but not exactly) issue to #95 I am having trouble initializing soundplay on an M2 mac. 

Where for the M1 described the issue was a

```
Could not start soundplayer 
ERROR: invalid soundplay binary name: soundplay.darwin.x86_64
```

For me the error is 

```
Error message: [Errno 86] Bad CPU type in executable: '/Users/ipasha/Software/RemoteObserving/soundplayer/soundplay.darwin.x86_64'
```

Based on a comment in #95 I tried not setting an executable name, but I get a Permission Denied on the soundplay folder when I try that (even when running sudo). 

Any advice? Happy to send full log if helpful.

**Comment by joshwalawender** [comment]
Can you show us the permissions on the soundplayer folder and the files in it?  That permissions error sounds suspicious.

**Comment by joshwalawender** [comment]
Also, try executing soundplayer directly.  Go to the `soundplayer` directory of the Remote Observing application and run:
`./soundplay.darwin.x86_64` via a terminal command line.

**Comment by prappleizer** [comment]
Hi Josh, 

Here's the direct attempt:
```
(kro) ipasha@Imads-MacBook-Pro soundplayer % ./soundplay.darwin.x86_64 
zsh: bad CPU type in executable: ./soundplay.darwin.x86_64
```

and these are the permissions on the soundplayer folder:
```
drwxr-xr-x  9 ipasha  staff     288 Oct 20 09:37 soundplayer
```
and the files in it

```
lrwxr-xr-x  1 ipasha  staff       22 Oct 20 09:37 soundplay -> soundplay.linux.x86_64
-rwxr-xr-x  1 ipasha  staff  6950935 Oct 20 09:37 soundplay.darwin.x86_64
-rwxr-xr-x  1 ipasha  staff  4870667 Oct 20 09:37 soundplay.linux.i686
-rwxr-xr-x  1 ipasha  staff  4512483 Oct 20 09:37 soundplay.linux.x86_64
-rwxr-xr-x  1 ipasha  staff  4061839 Oct 20 09:37 soundplay.raspbian.arm
-rwxr-xr-x  1 ipasha  staff  2938821 Oct 20 09:37 soundplay.solaris.sparc
-rwxr-xr-x  1 ipasha  staff  2309891 Oct 20 09:37 soundplay.solaris.x86
```

**Comment by joshwalawender** [comment]
It looks like your system is not correctly invoking the compatibility layer for macOS to run intel executables.  Can you try some of the solutions [here](https://apple.stackexchange.com/questions/408375/zsh-bad-cpu-type-in-executable) and see if that helps?

**Comment by prappleizer** [comment]
I just stumbled upon that too! I tried it and get the following 

```
(kro) ipasha@Imads-MacBook-Pro soundplayer % ./soundplay.darwin.x86_64
Note: using starkit mode "starpack" -- therefore, we
      do not try to load soundboard values from services file.
Using: afplay -v %v %s
Not using 'snack' package: can't find package snack
Using soundboard host: localhost
Using soundboard port: 9798
Can't connect to "localhost:9798": couldn't open socket: connection refused; retrying in 30 sec
```
Definitely progress, not sure whether I need to try installing this snack thing from somewhere, or something about freeing up sockets?

**Comment by joshwalawender** [comment]
That is a proper run of the file (we didn't give it valid inputs, that's where the other errors come from), so it works and you have the compatibility layer (rosetta).  Do you have two instances of `zsh` installed?  I'm not sure why the invocation of this (via python subprocess module) is not working.

**Comment by prappleizer** [comment]
No, the rosetta install fixed things! I tried running `./start_keck_viewers --test` again and the checks passed (and I got a sound). It was crackly, which was odd (I've seen that reported for other M2 macs though) but it's audible which is all that matters.

**Comment by joshwalawender** [comment]
Great! The test sound is inherently crackly, so that is normal on all machines.
