### ISSUE TITLE
dead URL anaconda

### ISSUE THREAD

**Issue by SteveAllen-UCOLick** [KeckObservatory/RemoteObserving#105]
the URL for anaconda is https://www.anaconda.com/distribution/
that gives 404

**Comment by joshwalawender** [comment]
Hi Steve,

Thanks, I’ve updated the readme to fix the bad link and tweak some language.

-Josh


From: SteveAllen-UCOLick ***@***.***>
Date: Monday, November 20, 2023 at 9:29 AM
To: KeckObservatory/RemoteObserving ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [KeckObservatory/RemoteObserving] dead URL anaconda (Issue #105)

the URL for anaconda is https://www.anaconda.com/distribution/
that gives 404
