### ISSUE TITLE
Can not bring up two different user sessions

### ISSUE THREAD

**Issue by joshwalawender** [KeckObservatory/RemoteObserving#3]
When supporting a multi-instrument night, it would be good to be able to bring up both sessions (e.g. HIRES and LRIS), but the second set of instrument VNCs fails because the ports are already in use.

Is there some way we can detect that and use different local ports?

**Comment by joshjriley** [comment]
I committed a fix for this to dev.  I'll do a pull request.  Can you test and confirm it works?

**Comment by joshwalawender** [comment]
Tested and confirmed.  Thanks!
