### ISSUE TITLE
no matching key exchange method found error

### ISSUE THREAD

**Issue by joshwalawender** [KeckObservatory/RemoteObserving#30]
@klanclos With the new ssh tunnel methods (not using the `sshtunnel` package), we get an error when creating a tunnel to older servers:

```
     INFO: Recieved command "status"
     INFO: Opening VNCviewer for 'status'
     INFO: Opening SSH tunnel for kvnc@svncserver1.keck.hawaii.edu:5901 on local port 50003.
Unable to negotiate with 128.171.95.113 port 22: no matching key exchange method found. Their offer: diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
^C    ERROR: Failed to open SSH tunnel for kvnc@svncserver1.keck.hawaii.edu:5901
```

We'll need a way to handle this.  Preferably on the call to ssh rather than having the user change a global configuration on their machine.

**Comment by klanclos** [comment]
This is the configuration file option that should make it work:

KexAlgorithms	+diffie-hellman-group1-sha1

There's probably a way to change this on the command line...

**Comment by klanclos** [comment]
...yes, here are the command line options:

ssh -o KexAlgorithms=+diffie-hellman-group1-sha1 sshserver1.keck.hawaii.edu

I'm having a hard time testing it though as I can't seem to trigger this error right now. The equivalent code change in open_ssh_tunnel() would look like:

        forwarding = f"{local_port}:localhost:{remote_port}"
        command = ['ssh', '-l', username, '-L', forwarding, '-N', '-T', server]
        command.append('-o')
        command.append('KexAlgorithms=+diffie-hellman-group1-sha1')
