### ISSUE TITLE
ERROR: Timeout during pytest

### ISSUE THREAD

**Issue by iancrossfield** [KeckObservatory/RemoteObserving#56]
Sometimes when running the `pytest` diagnostic, you'll get errors that look something like 
>     ERROR:   Timeout
and one or more failures will be indicated such as 
> FAILED test_basic_connectivity.py::test_connection_to_servers

**Comment by iancrossfield** [comment]
@joshwalawender reports (and I confirm) that the problem is intermittent and non-repeatable. The solution is to just keep trying `pytest` until everything works and you get no errors.

**Comment by joshwalawender** [comment]
@iancrossfield Can you try out the code in PR #57 to see if that resolves it?  I just extended the timeout period a bit.
