### ISSUE TITLE
Polling for SSH tunnel not waiting long enough

### ISSUE THREAD

**Issue by followthesheep** [KeckObservatory/RemoteObserving#76]
In creating the ssh tunnels, the code waits for about 5 seconds (check = 50 on line 333 of keck_vnc_launcher.py) before failing. check = 50 appears to be too short for some computers, so it times out before establishing a connection. I was able to check that establishing the tunnel manually works outside the script. When I changed check = 500, the script now works for this computer.

**Comment by joshwalawender** [comment]
I've extended the timeout to 10 seconds.  This will be released with the next point release.
