### ISSUE TITLE
Incorrect firewall password does not exit cleanly

### ISSUE THREAD

**Issue by joshjriley** [KeckObservatory/RemoteObserving#81]
When firewall password is entered incorrectly it results in a strange failure where code flounders around a bit doing other stuff after trying to exit app. App eventually exits, but this pushes the warning that the "API key is not set" off the screen.  We might want to fix this b/c this might come up a lot when we change the fw pass and some existing setups may not have setup their new API key.

**Comment by joshwalawender** [comment]
This appears to have been addressed in the current code version.
