### ISSUE TITLE
ssh commands timing out

### ISSUE THREAD

**Issue by bpholden** [KeckObservatory/RemoteObserving#92]
If the user has X11 forwarding enable and is connecting to a CentOS 7 or 8 host, the X11 connection will keep the ssh connection alive even if there is request for a single command such as a whoami.

The solution is simply to add the flag "-x" to the ssh command, as that will explicitly turn off X11 forwarding. 

One of the UCB remote hosts had this issue as did a couple of observers when connecting to the new Nickel VNC server.

**Comment by klanclos** [comment]
I think the WMKO scripts are covered against this failure mode, our ssh tunnels are only executed as subprocesses from the main script, and always include the -T (no TTY allocation) option. Our VNC servers are running CentOS 7 and it hasn't been an issue.

It's worth keeping this issue open until we test against CentOS 8 (or equivalent), which will likely occur for KPF.

**Comment by bpholden** [comment]
The explicit problem stated in the previous message involved the 
ssh host -T -N whoami

The -T option is not the issue. Including that still produces the problem. 
The -x option or having no X11 forwarding in the .ssh/config file is what is required.
