### ISSUE TITLE
Installing KRO on M1 Mac

### ISSUE THREAD

**Issue by alexji** [KeckObservatory/RemoteObserving#98]
I am installing KRO on a new M1 mac and found this problem:

```
> conda env create -f environment.yaml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - python=3.7
```

I think this is because anaconda does not have python 3.7 binaries for the M1, only 3.8 and later.

I was able to resolve this by editing the channel in environment.yaml from `conda-forge` to `conda-forge/osx-64` which forces the X86 install, but I'm wondering if there's a better/suggested solution?

**Comment by joshwalawender** [comment]
Hi @alexji , thanks for letting us know.  This should work under python 3.8+, so feel free to manually build a KRO environment using that.  I'll try to get the environment file updated.

**Comment by joshwalawender** [comment]
@alexji  File has been updated.  Feel free to do a `git pull` to get v2.0.11 and try the install again.  Thanks!
